### PR TITLE
Bump node16 -> node20

### PR DESCRIPTION
**Pull request by anderseknert**
Not sure if there's more to it than this, but let's try?

### CODE REVIEW

**Comment by srenatus** [comment]
🤷 LGTM. not sure if rebuilding dist/ is required or would (not) change anything.

**Comment by anderseknert** [comment]
I don't even understand what tools are required to do so, as I'm getting some quite cryptic errors running the scripts from package.json ... some developer docs would not have hurt 😅

**Comment by srenatus** [comment]
```
npm install
npm run prepare
```
would be my guess based on https://github.com/StyraInc/setup-regal/blob/main/package.json#L8

**Comment by anderseknert** [comment]
Thanks Stephan. I had apparently missed the install command prior to prepare. Now it works, but it generates identical files in the dist folder so there's nothing new to commit.

**Review by srenatus — APPROVED** [review]

**Pull request merged**
